# Generated by Django 4.2.5 on 2023-09-20 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_rename_resultspage_urlinputpagelanding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlinputpagelanding',
            name='content',
        ),
    ]
