# Generated by Django 4.2.5 on 2023-09-20 19:54

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_remove_urlinputpagelanding_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlinputpagelanding',
            name='content',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
