version: '3'
#Add following variables in .env file in same directory as this file
#SQL_ENGINE=django.db.backends.postgresql
#SQL_DATABASE=dbname
#SQL_USER=username
#SQL_PASSWORD=password
#SQL_HOST=dbimagename
#SQL_PORT=5432
#PORT=5432
#POSTGRES_DB=dbname
#POSTGRES_USER=username
#POSTGRES_PASSWORD=password
services:

  web:
    build: .
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:$PORT
    #command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      #- .:/code
      - .:/mysite
    #ports:
      #- 8000:8000
    expose:
      - 8000
    ports:
      - 8000:8000
    environment: 
      - PYTHONUNBUFFERED=1
      - PORT=8000
    user: wagtail
    env_file:
      - ./.env 
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=db_postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=q
    ports:
      - 5432:5432
    env_file:
      - ./.env

volumes:
  postgres_data:
