# Generated by Django 4.2.5 on 2023-10-11 14:07

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("django_comments_xtd", "0008_auto_20200920_2037"),
        ("blog", "0011_videoblogpage_articleblogpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomComment",
            fields=[
                (
                    "xtdcomment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="django_comments_xtd.xtdcomment",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customcomments",
                        to="blog.blogpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
                "ordering": ("submit_date",),
                "permissions": [("can_moderate", "Can moderate comments")],
                "abstract": False,
            },
            bases=("django_comments_xtd.xtdcomment",),
        ),
    ]
